name: Test the Lab 2 of Code
on: push
jobs:
  test-syntax-lab2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - id: upper_action
        uses: ./.github/actions/
        with:
          text: GitHub Action Rocks

      - run: |
          echo "Uppercase result: ${{ steps.upper_action.outputs.text }}"